# Generated by Django 5.1.2 on 2024-10-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Комплектуючі', 'verbose_name_plural': 'Комплектуючі'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Модель для обладнання', 'verbose_name_plural': 'Модель для обладнання'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'verbose_name': 'Тип обладнання', 'verbose_name_plural': 'Тип обладнання'},
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='component',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.equipment', verbose_name='Компонент'),
        ),
        migrations.AlterField(
            model_name='component',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='component',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='component',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Інвентаризаційний номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('in_use', 'Використовується'), ('in_repair', 'В ремонті'), ('on_stock', 'На складі'), ('disposed', 'Списане')], max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.equipmenttype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warranty_expiry_date',
            field=models.DateField(verbose_name='Гарантія'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
